### ISSUE TITLE
tip, installing/cloning, Z_SCHEMA_THING_T

### ISSUE THREAD

**Issue by larshp** [se38/SchemA#3]
Hi Uwe,
When installing the repository there is a manual step to activate table type Z_SCHEMA_THING_T, as it refers to class zcl_schema_thing. 

abapGit will try to activate all DDIC objects first, and then the code, I've not found any nice solution to handle the issue above. 

However, if Z_SCHEMA_THING_T is defined as a eg. public type in eg. class zcl_schema_thing, the type definition is part of the code, and there is no DDIC <-> code dependency. In this case abapGit will guide the user through the activation and activate all objects without manual user steps required.

**Comment by se38** [comment]
yes, this is as always the same problem with dependenses. I have the same with my JSON class.
I think I'll follow your suggestion (not really clean, but easier to handle).

For abapGIT I would suggest a checkbox like "Activate objects after import".

**Comment by larshp** [comment]
I agree its not really clean, but it works really well for the user installing the project.

I'm not sure I understand the use of the checkbox, would it in this case be used to disable the automatic guide/wizard for activating the objects?

**Comment by se38** [comment]
Yes, import and save, but not activate. Than it's also possible to import sources with Syntax Errors (for example if the basis version is to old and you want to correct this later)

**Comment by larshp** [comment]
currently the steps in abapGit are:
1: import all objects as inactive objects
2: trigger activation of DDIC objects with popup
3: trigger activation of other objects with popup

objects with syntax errors or other kinds of errors are saved in the system in step 1. Step 2 + 3 could be skipped, but then the user would have to go and try activating the same manually.

Ideally would be if the user is guided through all activation. Perhaps adding a step 4, which will try activating DDIC objects from step 2 that had not been activated, it would probably work in this case if the user pressed "activate anyhow" during step 3.
